### ISSUE TITLE
Emsa Lite result module issue

### ISSUE THREAD

**Issue by AaronITCL** [EnergyWater/EMSA#78] opened 2018-04-05 06:07 UTC
As you can see in the picture, the charts are not shown and the page repeats itselfs below.

![image](https://user-images.githubusercontent.com/33861863/38349530-d1598850-38a7-11e8-9b67-ea6ddd9def22.png)

**Comment by WINGSTeam** [comment] 2018-04-06 17:08
The problem is now fixed. You can check it as well.

**Closed as completed by WINGSTeam** 2018-04-06 17:08 UTC
Labels: bug, NEW feedback
