### ISSUE TITLE
Efficiency Score displayed as 0/100

### ISSUE THREAD

**Issue by MPetrakkas** [EnergyWater/EMSA#76] opened 2018-03-20 15:36 UTC
I have been facing the same problem in two validation cases 'Sludge Granulation and Watering & descaling), as the efficiency score I keep getting is Zero
![image](https://user-images.githubusercontent.com/37288518/37664565-3dd36582-2c64-11e8-8953-df1b7b744d75.png)
The values under "Best in EMSA tool" are very low as you can see and I am sot sure if this is the root of the problem.
![image](https://user-images.githubusercontent.com/37288518/37664979-f02120ee-2c64-11e8-9f8e-04a31aaa0063.png)
as you can see optimum is present but again an extraordinary low value that affects the displayed results
![image](https://user-images.githubusercontent.com/37288518/37665098-3435797e-2c65-11e8-92c6-3623abc94cf6.png)
the energy consuption data have however been included

**Comment by WINGSTeam** [comment] 2018-03-21 13:31
The problem is fixed now. You can check it as well. Thanks.

**Closed as completed by WINGSTeam** 2018-03-21 13:31 UTC
Labels: Calculations, help needed
