### ISSUE TITLE
Energy Consumption Results

### ISSUE THREAD

**Issue by MPetrakkas** [EnergyWater/EMSA#81] opened 2018-04-20 10:27 UTC
There seems to be a calculation problem when putting 1k units or 10k units as in the RESULTS the section with TOTAL ENERGY CONSUMPTION PER UNIT PRODUCTION take into account the number of units and doesn't divide it by 10K or 1K.
Therefore the energy consuption per unit production is much higher 1,000x or 10,000x than the expected

**Comment by WINGSTeam** [comment] 2018-04-26 13:37
The problem is now fixed. The calculation is correct.

**Closed as completed by WINGSTeam** 2018-04-26 13:37 UTC
Labels: NEW feedback, Calculations
